# Deploy to GitHub Pages with Data Update
name: Deploy to Pages

on:
  # Runs on a new tagged release
  release:
    types: [published]
  # Run weekly on Sunday at 00:00 UTC
  schedule:
    - cron: "0 0 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v6.2.0
        with:
          go-version: "1.21"
          check-latest: true

      - name: Build
        run: go build -v ./cmd/get_spoons

      - name: Fetch Venue Data
        env:
          JDW_TOKEN: ${{ secrets.JDW_TOKEN }}
        run: ./get_spoons -json -output venues.json

      - name: Fetch Venue Data (Expanded)
        env:
          JDW_TOKEN: ${{ secrets.JDW_TOKEN }}
        run: ./get_spoons -json -menus -items -output venues_expanded.json

      - name: Bake Data
        run: |
          echo "window.SPOONS_DATA = " > web/data.js
          cat venues_expanded.json >> web/data.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload web directory
          path: "./web"

      - name: Upload Data
        uses: actions/upload-artifact@v4
        with:
          # Upload venues.json
          path: "./venues.json"

      - name: Upload Expanded Data
        uses: actions/upload-artifact@v4
        with:
          # Upload venues_expanded.json
          path: "./venues_expanded.json"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
